### ISSUE TITLE
Not sure about results

### ISSUE THREAD

**Issue by goranskular** [simphotonics/directed_graph#2]
Hi, I tried to use crawler.paths, but it is not returning results I expected. What I am doing wrong? I used DirectedGraph.fromData() with custom object that has == operator and hashCode override.

print(crawler.paths(graph.vertices[3],
          graph.vertices[2])) result:

 
```
I/flutter ( 1739): {
I/flutter ( 1739):  M0IAX: [9A1FM, OH8STN, 9A1GS],
I/flutter ( 1739):  9A1FM: [M0IAX, OH8STN],
I/flutter ( 1739):  OH8STN: [M0IAX, 9A1FM],
I/flutter ( 1739):  9A1GS: [M0IAX, 9A1FM],
...
I/flutter ( 1739):  9A1AS: [M0IAA],
I/flutter ( 1739):  M0IAA: [],
I/flutter ( 1739):  9A3GS: [OH8TN],
I/flutter ( 1739):  OH8TN: [],
I/flutter ( 1739):  M1IAX: [OH2STN],
I/flutter ( 1739):  OH2STN: [],
I/flutter ( 1739):  OH8STZ: [M0AXA],
I/flutter ( 1739):  M0AXA: [],
I/flutter ( 1739):  9A2GS: [9A1GS],
I/flutter ( 1739): }

```
crawler.paths result:

`[[9A1GS, M0IAX, 9A1FM, M0IAX, OH8STN], [9A1GS, M0IAX, 9A1FM, M0IAX, 9A1GS, 9A1FM, OH8STN], [9A1GS, M0IAX, 9A1FM, OH8STN], [9A1GS, M0IAX, OH8STN]]`

I expected something like::
```
OK, FOUND:  [9A1GS, M0IAX, OH8STN], 
NOT FOUND: [9A1GS, 9A1FM, OH8STN], 
NOT FOUND: [9A1GS, 9A1FM, M0IAX, OH8STN]
```

graph.shortestPath result:

`OK: [M0IAX, OH8STN] (the same length is [9A1FM, OH8STN], which is missing, but ok)`

**Comment by simphotonics** [comment]
Hi @goranskular, it has nothing to do with you overriding the `==` operator. The problem is that the graph you are analyzing is cyclic.

It has the following structure: 
![graph](https://user-images.githubusercontent.com/5442704/92359634-805c5a80-f0e3-11ea-93c4-4f8d13754a2d.png)
and you are trying to find paths connecting D and C. 

The method `crawler.paths(start, target)` you are mentioning above uses a depth-first-search algorithm and  produces: 
`[[D, A, B, A, C], [D, A, B, A, D, B, C], [D, A, B, C], [D, A, C]]`. In this particular case, it omits the path `[D, B, C]` since the edge `[D, B]` has already been walked. 

To find the shortest paths *first*, I have changed the algorithm of the crawler methods `path()` and `paths()`. The updated version constructs a tree-like structure with the `start` vertex as root and then collects the branches ending with the `target` vertex.  To make things more transparent I introduced the parameter `maxWalkCount` which defaults to 1. For a cyclic path, the higher `maxWalkCount` the more paths will be found. 

Paths from D to C, with `maxWalkCount`: 1:
`[[D, A, C], [D, B, C]]`

Paths from D to C, `maxWalkCount`: 2
`[[D, A, C], [D, B, C], [D, A, B, C], [D, B, A, C]]`

Paths from D to C, `maxWalkCount`: 3
`[[D, A, C], [D, B, C], [D, A, B, C], [D, B, A, C], [D, A, B, A, C], [D, A, C, B, C]]`

**Comment by simphotonics** [comment]
In the latest (null-safe) version of `directed_graph` the definition of path has been tightened. It now refers to a list of connected vertices where inner vertices must not be listed twice. 

The path search algorithms have been updated to reflect the changes.
