### ISSUE TITLE
Add a wrapper around transitiveClosure from collection

### ISSUE THREAD

**Issue by modulovalue** [simphotonics/directed_graph#3]
This seems like a great fit for directed_graph.
[transitiveClosure](https://pub.dev/documentation/collection/latest/collection/transitiveClosure.html).

**Comment by simphotonics** [comment]
Thanks for your suggestion, completely agree. I was anyway thinking of storing edges in a structure of type `Map<T, Set<T>>`, see branch `null_safety`. 

I will add a factory constructor when merging the two branches. 
```Dart
import 'package:collection/collection.dart';

/// Factory constructor that returns the transitive closure of  [directedGraph].
factory DirectedGraph.transitiveClosure(DirectedGraph<T> directedGraph) => DirectedGraph(
  transitiveClosure(directedGraph.data),
  comparator: directedGraph.comparator,
);
```

**Comment by modulovalue** [comment]
Awesome, thanks :)

**Comment by simphotonics** [comment]
Added the factory constructors `DirectedGraph.transitiveClosure` and `WeightedDirectedGraph.transitiveClosure`. 

Instead of the function provided by `collection` I am using a recursive algorithm which seems to be faster. For the directed graph featured in the examples the benchmark show an execution time of 75us vs 500us.
